GET http://localhost:8081/api/v1/pacientes

###

POST http://localhost:8081/api/v1/auth/signin 
content-type: application/json

{
"usuario": "admin", "senha": "admin"
}

###

GET http://localhost:8081/api/v1/pacientes/1

###

GET http://localhost:8081/api/v1/pacientes/nome/son

###

GET http://localhost:8081/api/v1/pacientes/busca/?nome=son

###
POST http://localhost:8081/api/v1/pacientes
Content-Type: application/json

{
    "nome": "Cleberson",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-17T00:00:00"
}

###

POST http://localhost:8081/api/v1/pacientes
Content-Type: application/json

{
    "nome": "Danielson",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-15T00:00:00"
}
###

POST http://localhost:8081/api/v1/pacientes
Content-Type: application/json

{
    "id": 1,
    "nome": "Ceaser",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-15T00:00:00"
}

###

PUT http://localhost:8081/api/v1/pacientes/3465
Content-Type: application/json

{
    "nome": "Jonazinho",
    "sexo": "Masculino",
    "dataNascimento": "2022-08-15T00:00:00"
}

###

DELETE http://localhost:8081/api/v1/pacientes/4
